# Generated by Django 4.2.6 on 2023-10-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_creation', models.DateField()),
                ('date_of_last_edit', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('wiki_link', models.URLField(max_length=256)),
                ('in_person_event', models.BooleanField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
