# Generated by Django 4.2.4 on 2023-08-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profile_image', models.URLField(max_length=256)),
                ('profile_header', models.URLField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('wiki_link', models.URLField(max_length=256)),
                ('date_of_creation', models.DateField()),
                ('date_of_last_edit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_profile.profile')),
                ('self_learning', models.URLField(max_length=256)),
            ],
            bases=('user_profile.profile',),
        ),
        migrations.CreateModel(
            name='Skill_Family',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_profile.profile')),
            ],
            bases=('user_profile.profile',),
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_profile.profile')),
                ('birthday', models.DateField()),
                ('pronouns', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128)),
                ('twitter', models.CharField(max_length=50)),
                ('discord', models.CharField(max_length=50)),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.language')),
                ('skills_known', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_known', to='user_profile.skill')),
                ('skills_to_learn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_to_learn', to='user_profile.skill')),
            ],
            bases=('user_profile.profile',),
        ),
        migrations.AddField(
            model_name='skill',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.skill_family'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_creation', models.DateField()),
                ('date_of_last_edit', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('wiki_link', models.URLField(max_length=256)),
                ('in_person_event', models.BooleanField()),
                ('country', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.user_profile')),
            ],
        ),
    ]
