# Generated by Django 4.2.6 on 2023-10-10 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, unique=True, verbose_name='Organization name')),
                ('organization_website', models.URLField(error_messages={'unique': 'This website is already used by another organization.'}, unique=True, verbose_name='Organization website')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=128, verbose_name='Area name')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=128, verbose_name='Language name')),
                ('language_code', models.CharField(max_length=10, unique=True, verbose_name='Language code')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=128, unique=True, verbose_name='Region name')),
                ('parent_region', models.ManyToManyField(to='user_profile.region', verbose_name='Parent region')),
            ],
        ),
        migrations.CreateModel(
            name='WikimediaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikimedia_project_name', models.CharField(max_length=128, verbose_name='Wikimedia project name')),
                ('wikimedia_project_code', models.CharField(max_length=40, unique=True, verbose_name='Wikimedia project code')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.JSONField(null=True, verbose_name='Groups')),
                ('username', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='Username')),
                ('pronoun', models.CharField(blank=True, choices=[('he-him', 'He/Him'), ('she-her', 'She/Her'), ('they-them', 'They/Them')], max_length=20, null=True, verbose_name='Pronoun')),
                ('profile_image', models.URLField(verbose_name='Profile image')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Last name')),
                ('display_name', models.CharField(max_length=387, null=True, verbose_name='Display name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('twitter', models.CharField(blank=True, max_length=128, null=True, verbose_name='Twitter handle')),
                ('facebook', models.CharField(blank=True, max_length=128, null=True, verbose_name='Facebook handle')),
                ('instagram', models.CharField(blank=True, max_length=128, null=True, verbose_name='Instagram handle')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'This email is already in use.'}, max_length=254, null=True, unique=True)),
                ('contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('wiki', 'Discussion page')], max_length=10, null=True, verbose_name='Preferred contact method')),
                ('affiliation', models.ManyToManyField(related_name='user_affiliation', to='user_profile.affiliation', verbose_name='Affiliation')),
                ('area_of_interest', models.ManyToManyField(related_name='user_area_of_interest', to='user_profile.areaofinterest', verbose_name='Area of interest')),
                ('language', models.ManyToManyField(related_name='user_language', to='user_profile.language', verbose_name='Language')),
                ('region', models.ManyToManyField(related_name='user_region', to='user_profile.region', verbose_name='Region')),
                ('skills_known', models.ManyToManyField(related_name='user_skils', to='skills.skill', verbose_name='Skill known')),
                ('skills_wanted', models.ManyToManyField(related_name='user_desired_skils', to='skills.skill', verbose_name='Skill desired')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wikimedia_project', models.ManyToManyField(related_name='user_wikimedia_project', to='user_profile.wikimediaproject', verbose_name='Wikimedia project')),
            ],
        ),
    ]
