# Generated by Django 4.2.6 on 2023-10-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('user_profile', '0003_alter_region_parent_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation',
            field=models.ManyToManyField(blank=True, related_name='user_affiliation', to='user_profile.affiliation', verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='area_of_interest',
            field=models.ManyToManyField(blank=True, related_name='user_area_of_interest', to='user_profile.areaofinterest', verbose_name='Area of interest'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=387, null=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.JSONField(blank=True, null=True, verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='user_language', to='user_profile.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True, verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='user_region', to='user_profile.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills_known',
            field=models.ManyToManyField(blank=True, related_name='user_skils', to='skills.skill', verbose_name='Skill known'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills_wanted',
            field=models.ManyToManyField(blank=True, related_name='user_desired_skils', to='skills.skill', verbose_name='Skill desired'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wikimedia_project',
            field=models.ManyToManyField(blank=True, related_name='user_wikimedia_project', to='user_profile.wikimediaproject', verbose_name='Wikimedia project'),
        ),
    ]
