# Generated by Django 4.2.6 on 2023-10-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='organization_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Organization code'),
        ),
    ]
