# Generated by Django 4.2.6 on 2023-10-30 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profile_image', models.URLField(max_length=256)),
                ('profile_header', models.URLField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('wiki_link', models.URLField(max_length=256)),
                ('date_of_creation', models.DateField()),
                ('date_of_last_edit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profile_image', models.URLField(max_length=256)),
                ('profile_header', models.URLField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('wiki_link', models.URLField(max_length=256)),
                ('date_of_creation', models.DateField()),
                ('date_of_last_edit', models.DateField()),
                ('self_learning', models.URLField(max_length=256)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill_family')),
            ],
        ),
    ]
